# Generated by Django 5.1.2 on 2024-10-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram_id')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('file', models.FileField(upload_to='music_files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
